### ISSUE TITLE
UCSF Profile page for Saurabh

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-CBC/CBC-website#1]
Saurabh (@graft) needs a UCSF Profile page and link to it from http://cbc.ucsf.edu/people/ like for the rest of us.

@rituroy, could you please explain to him what you did to get one for yourself.

BTW, folks, I've renamed the repository from 'website' to 'CBC-website' - you might need to update your local git configs if you're already got it downloaded locally.

**Comment by graft** [comment]
I applied for one, I'm waiting for the profiles people to get back to me.

**Comment by HenrikBengtsson** [comment]
Linking to Saurabh's UCSF Profile from http://cbc.ucsf.edu/people/
Also, added Saurabh to the publication page http://cbc.ucsf.edu/publications/
