### ISSUE TITLE
Add Mark Segal

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-CBC/CBC-website#2]
Add Mark Segal (http://profiles.ucsf.edu/mark.segal) to CBC site:

1. [x] Have Mark sign up on GitHub
2. [x] Add paragraph to http://cbc.ucsf.edu/people/
3. [x] Add Mark to http://cbc.ucsf.edu/publications/
4. [x] Add Mark to http://cbc.ucsf.edu/contact/

**Comment by HenrikBengtsson** [comment]
I've added Mark to all relevant pages (people, publications and contact). For the [people](http://cbc.ucsf.edu/people/) page, I just made a simple stub.

@marksegal, please expand the paragraph on yourself by editing https://github.com/UCSF-CBC/CBC-website/blob/master/content/people/index.md (you can edit online).  Let me know when done and I'll make it available on our website.

**Comment by marksegal** [comment]
Done.

On 3 Sep 2015, at 12:24 pm, Henrik Bengtsson <notifications@github.com<mailto:notifications@github.com>>
 wrote:


I've added Mark to all relevant pages (people, publications and contact). For the people<http://cbc.ucsf.edu/people/> page, I just made a simple stub.

@marksegal<https://github.com/marksegal>, please expand the paragraph on yourself by editing https://github.com/UCSF-CBC/CBC-website/blob/master/content/people/index.md (you can edit online). Let me know when done and I'll make it available on our website.

—
Reply to this email directly or view it on GitHub<https://github.com/UCSF-CBC/CBC-website/issues/2#issuecomment-137547891>.

******************************************************************

Mark R. Segal, PhD

Professor,  Department of Epidemiology and Biostatistics

Director,  Center for Bioinformatics & Molecular Biostatistics

Head, Division of Bioinformatics

University of California at San Francisco

550 16th Street, 2nd Floor, Box #0560
San Francisco, CA 94158-2549


e-mail: mark.segal@.ucsf.edu<http://ucsf.edu>

voice: (415) 514-8034

fax:   (415) 514-8150

http://profiles.ucsf.edu/mark.segal

******************************************************************

**Comment by HenrikBengtsson** [comment]
Thanks. Webpage rebuilt and updated.
