### ISSUE TITLE
Add job ad

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-CBC/CBC-website#8]

**Comment by olshena** [comment]
Henrik, with these links please make the post:

III level position:

https://trm128.brassring.com/Requisition/View?reqid=2448928&formtypeid=561&reqlanguage=en&emailkey=11405&uid=
^ZxbEBaC4*9tJBqdTJBjSsA==&isstatusnotificationflow=true

iv level position:

https://trm128.brassring.com/Requisition/View?reqid=2449047&formtypeid=561&reqlanguage=en&emailkey=15430&uid=
^*ZLSHC67ALIRNXMoanFxog==&isstatusnotificationflow=true

**Comment by HenrikBengtsson** [comment]
Neither of these links work.  Try in Chrome's "Incognito-mode".  Ask them for public URLs or see if there's an option to "share" job post via email; if so, email yourself and retry with whatever URL you receive.

**Comment by olshena** [comment]
The link is being cut off.  If you cut-and-paste the whole link it will
work.

On Tue, Feb 14, 2017 at 11:28 AM, Henrik Bengtsson <notifications@github.com

**Comment by HenrikBengtsson** [comment]
Nope, see yourself in Chrome's "Incognito-mode".

FYI, you if you put a string within backticks - e.g. `https://trm128.brassring.com/Requisition/View?reqid=2448928&formtypeid=561&reqlanguage=en&emailkey=11405&uid=
^ZxbEBaC4*9tJBqdTJBjSsA==&isstatusnotificationflow=true` - you'll make it verbatim and it's easier to cut'n'paste.  Or even better, tripple backtick code sections;
```
https://trm128.brassring.com/Requisition/View?reqid=2448928&formtypeid=561&reqlanguage=en&emailkey=11405&uid=
^ZxbEBaC4*9tJBqdTJBjSsA==&isstatusnotificationflow=true
```

**Comment by olshena** [comment]
I got new links by sending to myself.  Do these work?  Works for me in
incognito mode.

III
https://sjobs.brassring.com/tgwebhost/jobdetails.aspx?jobId=
2448928&PartnerId=6495&SiteId=5226&type=mail&JobReqLang=1&
recordstart=1&JobSiteId=5226&JobSiteInfo=2448928_5226&gqid=0

Iv

https://sjobs.brassring.com/tgwebhost/jobdetails.aspx?
jobId=2449047&PartnerId=6495&SiteId=5226&type=mail&
JobReqLang=1&recordstart=1&JobSiteId=5226&JobSiteInfo=2449047_5226&gqid=0




On Tue, Feb 14, 2017 at 11:40 AM, Henrik Bengtsson <notifications@github.com

**Comment by HenrikBengtsson** [comment]
I'm confirming these works for me and also from outside the UCSF network.  I'll add.

**Comment by olshena** [comment]
I don't see anything.  Please add as soon as you can.

On Tue, Feb 14, 2017 at 11:47 AM, Henrik Bengtsson <notifications@github.com

**Comment by HenrikBengtsson** [comment]
Aren't your updates on http://cbc.ucsf.edu/openings/ - are you done with the edits?

**Comment by olshena** [comment]
I am done with edits.  But last time there was a link from the front page.

On Wed, Feb 15, 2017 at 10:37 AM, Henrik Bengtsson <notifications@github.com

**Comment by HenrikBengtsson** [comment]
I'll add that now; I wanted to make sure the text was done before doing that.

**Comment by olshena** [comment]
Thanks.  Please double check my edits for accuracy.

On Wed, Feb 15, 2017 at 10:41 AM, Henrik Bengtsson <notifications@github.com

**Comment by HenrikBengtsson** [comment]
It's now live at http://cbc.ucsf.edu/
